# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Bruce"
resume_title:                   "运维工程师|DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "zhengma0211@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "18779999999"
resume_contact_address:         "87 WanNian"

resume_header_contact_info:     "87 WanNian • 18779999999 • zhengma0211@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>十余年运维老兵，热爱学习，热衷专研，笃信运维从标准化，到脚本化，再到自动化，继而规模化。深知运维安全的重要性，既不停扩展运维领域的广度，也不断深耕特定技术的深度；从系统的服务器指标监控，到业务层的日志监控，再到更高层次的应用链路监控（可观测性平台），从虚拟化，到容器化，再到k8s，或者上云的选型；当然还有持续集成持续发布（CICD），为系统的快速更新迭代保驾护航。期待与贵司的合作。</p><p>A seasoned veteran with over a decade of experience in operations and maintenance, I am passionate about continuous learning and dedicated to in-depth exploration. I firmly believe in the evolution of operations, progressing from standardization to scripting, automation, and ultimately scaling. Recognizing the criticality of operational security, I consistently expand the breadth of my expertise while delving into the depths of specific technologies. My journey spans from monitoring server metrics at the system level to log monitoring at the business layer, and further to high-level application chain monitoring(observability platforms). I have navigated through virtualization, containerization, Kubernetes, and cloud adoption. Additionally, I am well-versed in Continuous Integration and Continuous Deployment (CICD), ensuring seamless and secure facilitation of rapid system updates and iterations. I look forward to the opportunity to collaborate with your esteemed company.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
